"""Initial migration - Add AV_segmented column to StorageModel

Revision ID: 94c890fd2e44
Revises: 
Create Date: 2024-08-15 21:50:40.150290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c890fd2e44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AV_segmented', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_model', schema=None) as batch_op:
        batch_op.drop_column('AV_segmented')

    # ### end Alembic commands ###
